name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - jsenv
      - ocamlenv

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: edmcman/cposc-fun
